In [10]:
# # Day 1 - Pandas Basics 🚀

# Today I learned:
# - What is Pandas
# - Series and DataFrame
# - Basic operations like head(), info(), describe()
# - Column selection and modification

In [11]:

import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
s = pd.Series([100, 200, 300], index=['A', 'B', 'C'])
s

A    100
B    200
C    300
dtype: int64

In [13]:
data = {
    'Name': ['Jay', 'Raj', 'Meet'],
    'Age': [20, 21, 19]
}

df = pd.DataFrame(data)
df

   Name  Age
0   Jay   20
1   Raj   21
2  Meet   19

In [14]:
df.head()   # first 5 rows
df.tail()   # last 5 rows

   Name  Age
0   Jay   20
1   Raj   21
2  Meet   19

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [6]:
df.describe()

        Age
count   3.0
mean   20.0
std     1.0
min    19.0
25%    19.5
50%    20.0
75%    20.5
max    21.0

In [7]:
df['Name']

0     Jay
1     Raj
2    Meet
Name: Name, dtype: object

In [8]:
df[['Name', 'Age']]

   Name  Age
0   Jay   20
1   Raj   21
2  Meet   19

In [9]:
df['Marks'] = [80, 90, 85]
df

   Name  Age  Marks
0   Jay   20     80
1   Raj   21     90
2  Meet   19     85