In [ ]:
# # Day 15 - Data Preprocessing & Feature Engineering 🚀

# ## Topics Covered:
# - Data Cleaning (missing values)
# - Feature Transformation
# - Encoding categorical data
# - Feature Scaling
# - Feature Engineering
# - Feature Selection

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Jay', 'Raj', 'Meet', 'Neel', 'Amit'],
    'Age': [20, 21, None, 22, 20],
    'Marks': [80, 90, 85, None, 75],
    'Department': ['IT', 'HR', 'IT', 'HR', 'IT']
}

df = pd.DataFrame(data)
df

   Name   Age  Marks Department
0   Jay  20.0   80.0         IT
1   Raj  21.0   90.0         HR
2  Meet   NaN   85.0         IT
3  Neel  22.0    NaN         HR
4  Amit  20.0   75.0         IT

In [3]:
df.isnull().sum()

Name          0
Age           1
Marks         1
Department    0
dtype: int64

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [5]:
df = df.drop('Name', axis=1)

In [6]:
df = pd.get_dummies(df, columns=['Department'])
df

     Age  Marks  Department_HR  Department_IT
0  20.00   80.0          False           True
1  21.00   90.0           True          False
2  20.75   85.0          False           True
3  22.00   82.5           True          False
4  20.00   75.0          False           True

In [7]:
df['Marks'] = (df['Marks'] - df['Marks'].mean()) / df['Marks'].std()

In [8]:
df['Performance'] = df['Marks'] * df['Age']
df

     Age     Marks  Department_HR  Department_IT  Performance
0  20.00 -0.447214          False           True    -8.944272
1  21.00  1.341641           True          False    28.174457
2  20.75  0.447214          False           True     9.279682
3  22.00  0.000000           True          False     0.000000
4  20.00 -1.341641          False           True   -26.832816

In [9]:
X = df[['Age', 'Marks']]
y = df['Performance']