In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Jay', 'Raj', 'Meet', 'Neel'],
    'Age': [20, 21, 19, 22],
    'Marks': [80, 90, 85, 70]
}

df = pd.DataFrame(data)
df

   Name  Age  Marks
0   Jay   20     80
1   Raj   21     90
2  Meet   19     85
3  Neel   22     70

In [3]:
df['Name']

0     Jay
1     Raj
2    Meet
3    Neel
Name: Name, dtype: object

In [4]:
df[['Name', 'Marks']]

   Name  Marks
0   Jay     80
1   Raj     90
2  Meet     85
3  Neel     70

In [5]:
df.loc[0]        # first row
df.loc[1:2]      # row 1 to 2

   Name  Age  Marks
1   Raj   21     90
2  Meet   19     85

In [6]:
df.iloc[0]       # first row
df.iloc[1:3]     # row 1 to 2

   Name  Age  Marks
1   Raj   21     90
2  Meet   19     85

In [7]:
df.loc[0:2, ['Name', 'Marks']]

   Name  Marks
0   Jay     80
1   Raj     90
2  Meet     85

In [8]:
df.iloc[0:2, 0:2]

  Name  Age
0  Jay   20
1  Raj   21

In [9]:
df[df['Marks'] > 80]

   Name  Age  Marks
1   Raj   21     90
2  Meet   19     85

In [10]:
df.sort_values(by='Marks')

   Name  Age  Marks
3  Neel   22     70
0   Jay   20     80
2  Meet   19     85
1   Raj   21     90