In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Jay', 'Raj', 'Meet', None],
    'Age': [20, None, 19, 22],
    'Marks': [80, 90, None, 70]
}

df = pd.DataFrame(data)
df

   Name   Age  Marks
0   Jay  20.0   80.0
1   Raj   NaN   90.0
2  Meet  19.0    NaN
3  None  22.0   70.0

In [3]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

In [4]:
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [5]:
df.dropna()

  Name   Age  Marks
0  Jay  20.0   80.0

In [6]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [7]:
df.fillna(0)

   Name   Age  Marks
0   Jay  20.0   80.0
1   Raj   0.0   90.0
2  Meet  19.0    0.0
3     0  22.0   70.0

In [8]:
df['Age'].fillna(df['Age'].mean())

0    20.000000
1    20.333333
2    19.000000
3    22.000000
Name: Age, dtype: float64