In [ ]:
# # Day 5 - GroupBy & Data Analysis 🚀

# Today I learned:
# - GroupBy operations
# - Aggregation functions (mean, max, min)
# - Value counts and unique values
# - Applying functions on data

In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Jay', 'Raj', 'Meet', 'Neel', 'Amit'],
    'Department': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Marks': [80, 90, 85, 70, 75]
}

df = pd.DataFrame(data)
df

   Name Department  Marks
0   Jay         IT     80
1   Raj         HR     90
2  Meet         IT     85
3  Neel         HR     70
4  Amit         IT     75

In [5]:
df.groupby('Department').mean()

<class 'TypeError'>: agg function failed [how->mean,dtype->object]

In [4]:
df.groupby('Department')['Marks'].mean()

Department
HR    80.0
IT    80.0
Name: Marks, dtype: float64

In [6]:
df.groupby('Department')['Marks'].agg(['mean', 'max', 'min'])

            mean  max  min
Department
HR          80.0   90   70
IT          80.0   85   75

In [7]:
df['Department'].value_counts()

Department
IT    3
HR    2
Name: count, dtype: int64

In [8]:
df['Department'].unique()

array(['IT', 'HR'], dtype=object)

In [9]:
df['Department'].nunique()

2

In [10]:
df['Marks'].apply(lambda x: x + 5)

0    85
1    95
2    90
3    75
4    80
Name: Marks, dtype: int64

In [11]:
df.rename(columns={'Marks': 'Score'})

   Name Department  Score
0   Jay         IT     80
1   Raj         HR     90
2  Meet         IT     85
3  Neel         HR     70
4  Amit         IT     75