In [10]:
# # Day 7 - Data Aggregation & Transformation 🚀

# ## Topics Covered:
# - groupby() for aggregation
# - apply() for transformation
# - merge() for joining data
# - concat() for combining data

In [11]:
import pandas as pd

In [12]:
data1 = {
    'ID': [1, 2, 3, 4],
    'Name': ['Jay', 'Raj', 'Meet', 'Neel'],
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Marks': [80, 90, 85, 70]
}

df1 = pd.DataFrame(data1)

data2 = {
    'ID': [1, 2, 3, 4],
    'City': ['Ahmedabad', 'Surat', 'Rajkot', 'Baroda']
}

df2 = pd.DataFrame(data2)

df1

   ID  Name Department  Marks
0   1   Jay         IT     80
1   2   Raj         HR     90
2   3  Meet         IT     85
3   4  Neel         HR     70

In [13]:
df1.groupby('Department')['Marks'].mean()

Department
HR    80.0
IT    82.5
Name: Marks, dtype: float64

In [14]:
df1.groupby('Department')['Marks'].agg(['mean', 'max', 'min'])

            mean  max  min
Department
HR          80.0   90   70
IT          82.5   85   80

In [15]:
df1['Marks'] = df1['Marks'].apply(lambda x: x + 5)
df1

   ID  Name Department  Marks
0   1   Jay         IT     85
1   2   Raj         HR     95
2   3  Meet         IT     90
3   4  Neel         HR     75

In [16]:
merged_df = pd.merge(df1, df2, on='ID')
merged_df

   ID  Name Department  Marks       City
0   1   Jay         IT     85  Ahmedabad
1   2   Raj         HR     95      Surat
2   3  Meet         IT     90     Rajkot
3   4  Neel         HR     75     Baroda

In [17]:
df_new = pd.concat([df1, df1])
df_new

   ID  Name Department  Marks
0   1   Jay         IT     85
1   2   Raj         HR     95
2   3  Meet         IT     90
3   4  Neel         HR     75
0   1   Jay         IT     85
1   2   Raj         HR     95
2   3  Meet         IT     90
3   4  Neel         HR     75